/*
 * access_agent_consts.h
 *
 *  Created on: Nov 19, 2019
 *      Author: gilbert
 */

#ifndef _ACCESS_AGENT_CONSTS_H_
#define _ACCESS_AGENT_CONSTS_H_

#define DEFAULT_LINE_BUUFER_SIZE	8192

#define DEFAULT_STR_LEN	256

#define FS_FIELD_DEFINE_FORWARD_IP	30

#define FS_FIELD_DEFINE_CLIENT_IP	12

#define FS_FIELD_DEFINE_METHOD	16

#define FS_FIELD_DEFINE_STATUS	27

#define FS_FIELD_DEFINE_TIME	23

#define FS_FIELD_DEFINE_INTERFACE	28

#define FS_FIELD_DEFINE_SERVICE_HOST	13

#define FS_FIELD_DEFINE_RESP_TIME	26

#define	DEFAULT_IP_ADDRESS_LEN	16

#define	DEFAULT_METHOD_LEN	8

#define	DEFAULT_STATUS_LEN	4

#define DEFUALT_RESP_TIME_LEN	8

#define DEFAULT_TIME_LEN	32

#define DEFAULT_SERVICE_LEN	32

#define DEFAULT_INF_LEN	64

#define DEFAULT_POOL_NAME	"fs_monitor_worker_pool"

#define DEFUALT_POOL_MAX_SIZE	64

#define INOTIFY_BUFFER_SIZE	1024

#define CFG_FIELD_NAME_DIR	"dir"

#define CFG_FIELD_NAME_FILE	"file"

#define CFG_FIELD_NAME_HOST	"host"

#define CFG_FIELD_NAME_PORT	"port"

#define CFG_MAX_ITEM	128

#endif /* _ACCESS_AGENT_CONSTS_H_ */
